
package soap.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentEndPoint", targetNamespace = "http://endpoint.soap/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentEndPoint {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://endpoint.soap/StudentEndPoint/updateRequest", output = "http://endpoint.soap/StudentEndPoint/updateResponse")
    public boolean update(
        @WebParam(name = "arg0", partName = "arg0")
        Student arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns soap.endpoint.Student
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://endpoint.soap/StudentEndPoint/createRequest", output = "http://endpoint.soap/StudentEndPoint/createResponse")
    public Student create(
        @WebParam(name = "arg0", partName = "arg0")
        Student arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns soap.endpoint.Student
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://endpoint.soap/StudentEndPoint/getEntityByIdRequest", output = "http://endpoint.soap/StudentEndPoint/getEntityByIdResponse")
    public Student getEntityById(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

}
